_target_: src.methods.deepar.DeepAR
num_layers: 1
dropout: 0
hidden_dim: 256
lr: 1e-3
val_samples: 5
test_samples: 100

# Конфиг-файл локального уровня, без package global
# тут можно указать только параметры самого метода.