# @package _global_

method:
  _target_: src.methods.GLaST.GLaST_legacy.GLaSTForecaster
  backbone: transformer #feednet or transformer
  input_len: 96
  output_len: 720
  var_num: 1  
  hidden_dim: 64  
  dropout: 0.1
  lr: 1e-3

patience: 10
trainer_args:
  max_epochs: -1