# @package _global_

# Parameters copied from TFM repo
method:
  _target_: src.methods.tfm.TrajectoryFlowMatching
  history: 3
  sigma: 0.1
  lr: 1e-6
  hidden_dim: 256
  val_samples: 50
  test_samples: 100

patience: 3
trainer_args:
  check_val_every_n_epoch: 50
  max_epochs: -1

# Конфиг-файл глобального уровня, с package global
# тут можно указать любые параметры, в частности 
# тут удобно менять  обучения (patience, check_val_every_n_epoch).
