_target_: src.methods.TSDiff.tsdiff.TSDiffCond
hidden_dim: 64
step_emb: 32 
timesteps: 100
dropout: 0
num_residual_blocks: 3
lr: 1e-3
num_samples: 3
noise_observed: False

# Конфиг-файл локального уровня, без package global
# тут можно указать только параметры самого метода.