#!/usr/bin/env bash
set -euo pipefail

DOCKER_NAME=${DOCKER_NAME:-devuser}                
SRC=${SRC:-project}                                  
CONTAINER_NAME=${CONTAINER_NAME:-devuser-time_series_generation}

DOCKER_USER_ID=${DOCKER_USER_ID:-1000}
DOCKER_GROUP_ID=${DOCKER_GROUP_ID:-1000}

echo "DOCKER_NAME=$DOCKER_NAME"
echo "SRC=$SRC"
echo "CONTAINER_NAME=$CONTAINER_NAME"
echo "DOCKER_USER_ID=$DOCKER_USER_ID"
echo "DOCKER_GROUP_ID=$DOCKER_GROUP_ID"

