#! /bin/bash

DOCKER_NAME=clast # username in container
SRC=$(basename $(pwd)) # source directory (supposedly, this repo's path is /home/${USER}/${SRC})
CONTAINER_NAME=$USER-time_series_generation # name of container

# to get these values type "id" in shell termilal
DOCKER_USER_ID=$(id -u) 
DOCKER_GROUP_ID=$(id -g)
