defaults:
 - _self_
 - benchmark: etth1s
 - method: LaST

trainer_args:
  max_epochs: 1
  devices: 1
  # check_val_every_n_epoch: 10

patience: 10
train_batch_size: 32
eval_batch_size: 512
num_workers: 16
seed: 0

hydra:
  job:
    chdir: false
