defaults:
 - method: tfm
 - benchmark: etth1s
 - _self_

trainer_args:
  max_epochs: -1
  devices: 1

monitor: val_mae
hidden_dim: 256
learning_rate: 1e-3
batch_size: 32
num_workers: 16
patience: 10
seed: 0
