defaults:
 - _self_
 - benchmark: weather-l
 - method: GLaST

trainer_args:
  max_epochs: -1
  devices: [0]
  # check_val_every_n_epoch: 10

patience: 10
train_batch_size: 64
val_batch_size: 1024 # Little samples => large batch size wo OOM
test_batch_size: 512 # Lots of samples => RAM OOM
num_workers: 16
seed: 20